version: '3'

services:
  database:
    container_name: mongo-api
    image: mongo
    environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=example
        - MONGO_INITDB_DATABASE=products_api
        - MONGO_INITDB_USERNAME=jagoda
        - MONGO_INITDB_PASSWORD=pass
    volumes:
      - db_data:/var/lib/mongodb:rw
    ports:
    - "27017:27017"

  php:
    container_name: php-api
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    image: sf-docker/php:dev
    restart: on-failure
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      PHP_DATE_TIMEZONE: ${PHP_DATE_TIMEZONE:-UTC}
      XDEBUG_CONFIG: client_host=host.docker.internal
      PHP_IDE_CONFIG: serverName=docker
    depends_on:
      - database
    ports:
      - "8033:8033"
      - "9000:9000"
      - "8022:8022"
    volumes:
      - .:/app:rw,cached
      - var:/app/var
    extra_hosts:
      - "host.docker.internal:host-gateway"



volumes:
  db_data:
  var:

